version: '3.8'

services:
  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Serviço do microserviço NestJS (sem Dockerfile)
  auth-service:
    image: node:18-alpine
    container_name: auth-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: 3600s
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: npm run start:prod
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
    postgres:
